<template>
  <div
    class="fixed bottom-10 right-10 z-50 flex size-12 cursor-pointer items-center justify-center rounded-full bg-[#dabb4b] text-black hover:bg-[#dabb4b]/90"
    data-cy="b4ceaeebf61471e6"
    @click="onNewSpacePrecheck"
  >
    <i class="fa-light fa-plus text-2xl" />
  </div>
</template>

<script>
import { paymentEvent } from '~/constant/eventBus';

export default {
  setup() {
    const authStore = useAuthStore();
    const hubSidebar = useHubSidebarStore();
    const hubSpaces = useHubSpacesStore();
    const paymentStore = usePaymentStore();

    return { authStore, hubSpaces, hubSidebar, paymentStore };
  },
  computed: {
    view() {
      return this.$route.query.view || 'grid';
    },
    user() {
      return this.authStore.user;
    },
    spaceId() {
      return this.$route.query.space;
    },
    folderId() {
      return this.$route.query.folder;
    },
    isFolder() {
      return !!this.folderId;
    },
    isSpace() {
      return !!this.spaceId && !this.isFolder;
    },
    space() {
      return this.hubSpaces.find(this.spaceId);
    },
    folder() {
      return this.hubSpaces.find(this.folderId);
    },
    hasServiceSubscription() {
      return this.authStore.hasServiceSubscription;
    },
  },
  mounted() {
    this.$eventBus.on(paymentEvent.SUB_SERVICE_SUCCESS, this.handleSubSuccess);
  },
  beforeUnmount() {
    this.$eventBus.off(paymentEvent.SUB_SERVICE_SUCCESS, this.handleSubSuccess);
  },
  methods: {
    onClick() {
      if (this.view === 'list' || (this.view === 'grid' && !this.spaceId)) {
        this.hubSidebar.state = true;
        this.hubSidebar.space.autoGenerated = true;
        return;
      }

      if (this.view === 'grid') {
        if (this.isSpace || this.isFolder) {
          this.hubSidebar.space.data = this.space;
          this.hubSidebar.children.state = true;
          this.hubSidebar.state = true;
        } else {
          this.hubSidebar.state = true;
        }
      }
    },
    onNewSpacePrecheck() {
      if (!this.hasServiceSubscription) {
        this.paymentStore.setServiceDialog(true);
      } else {
        this.onClick();
      }
    },
    handleSubSuccess() {
      this.onClick();
    },
  },
};
</script>
