runtime: nodejs18

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

instance_class: F4

automatic_scaling:
  min_instances: 1
  max_instances: 11
  target_cpu_utilization: 0.6

env_variables:
  NODE_ENV: production
  BRANCH_NAME: prod
  PORT: '8080'
