<template>
  <div class="flex flex-col gap-2">
    <OrganizationHubCalendarSidebarTitle
      :title="$t('calendar.label')"
      :open="open"
      @on-open="onOpen"
      @on-change="onSearch"
    >
      <i class="fa-regular fa-calendars text-[#707070]" />
      <template #after>
        <div
          data-cy="calendar-create-icon"
          class="relative flex h-6 w-6 cursor-pointer items-center justify-center rounded-5 text-[#f1f1f1] transition-all hover:bg-white/5 active:scale-95"
          @click="onCreate"
        >
          <i
            class="fa-light text-xs"
            :class="loading ? 'fa-loader animate-spin' : 'fa-plus'"
          />
        </div>
      </template>
    </OrganizationHubCalendarSidebarTitle>
    <div v-if="open" class="w-full flex-col gap-2 px-2">
      <OrganizationHubCalendarSidebarCalendarsItem
        v-for="item in dataList"
        :key="item.id"
        :item="item"
        :query="name"
        :data-cy="`${item.id}-list-of-calanders`"
      />
    </div>
  </div>
</template>

<script>
export default {
  setup() {
    const hubCalendarStore = useHubCalendarStore();
    const authStore = useAuthStore();
    const hubSidebar = useHubSidebarStore();
    return { hubCalendarStore, authStore, hubSidebar };
  },
  data() {
    return {
      open: true,
      name: '',
      loading: false,
    };
  },
  computed: {
    dataList() {
      return this.hubCalendarStore.calendarList.filter(
        (r) =>
          ((this.authStore.isUser && r.owner.type === 'profile') ||
            !this.authStore.isUser) &&
          r.name.toLowerCase().includes(this.name.toLowerCase()),
      );
    },
  },
  methods: {
    onSearch(name) {
      this.name = name;
    },
    onOpen(open) {
      this.open = open;
    },
    async onCreate() {
      this.hubSidebar.state = false;
      this.hubSidebar.calendar.state = false;
      this.loading = true;
      const data = await this.hubCalendarStore.createCalendar({
        autoGenerated: true,
        timezone: this.authStore?.user?.timezone,
      });
      await this.$nextTick();
      this.loading = false;
      this.hubSidebar.calendar.data = data;
      this.hubCalendarStore.dateTypeIndex = 1;
      this.hubSidebar.state = true;
      this.hubSidebar.calendar.state = true;
      if (this.$device.isMobile) {
        this.hubCalendarStore.sidebarOpen = false;
      }
    },
  },
};
</script>
