export const useHubSidebarStore = defineStore('hubSidebar', {
  state: () => ({
    state: false,
    calendar: {
      state: false,
      detailState: false,
      scheduleState: false,
      data: {},
    },
    space: {
      state: false,
      creating: false,
      autoGenerated: false,
      data: {},
    },
    payment: {
      state: false,
    },
    sort: {
      state: false,
    },
    course: {
      created: false, // 课程创建成功
      state: false, // 普通课程
      purchasedByOrg: false, // 组织购买的课程
      folder: {},
      data: {},
    },
    children: {
      state: false,
      loading: false,
      folderCreating: false,
    },
    builder: {
      state: false,
    },
    invite: {
      type: 'space', // space, course, room, calendar
      state: false,
      infoState: false,
      selecteds: [],
    },
    version: {
      state: false,
    },
    log: {
      state: false,
    },
    license: {
      state: false,
      assign: false,
      manage: false,
      groups: false,
      group: {},
    },
  }),
  actions: {
    async edieCourse({ course, isBuilder = false }) {
      const authStore = useAuthStore();
      const hubSpaces = useHubSpacesStore();
      const editable = hubSpaces.checkCourseEditable(course);

      this.course.state = false;
      this.course.purchasedByOrg = false;
      await nextTick();

      this.course.folder = hubSpaces.find(course._folderId);
      this.space.data = hubSpaces.find(course._spaceId);
      this.course.data = course;
      this.children.state = true;
      this.builder.state = isBuilder;
      this.state = true;

      if (authStore.isOrg && !editable) {
        // course.purchased ???
        this.course.purchasedByOrg = true;
      } else {
        this.course.state = true;
      }
    },
    async createSidebarCourse({ space, folder }) {
      this.space.data = space;
      this.children.state = true;
      this.state = true;
      await sleep(1000);
      const $button = document.querySelector(
        `[data-new-course-folder-id="${folder.id}"]`,
      );
      $button?.click();
    },
    async createSidebarFolder({ space }) {
      this.space.data = space;
      this.children.state = true;
      this.state = true;
      await sleep(500);
      const $button = document.querySelector('#sidebar-new-folder');
      $button?.click();
    },
  },
});
