<template>
  <OrganizationHubSidebarWrap v-loading="creating" :open="open">
    <div
      class="mb-2 flex h-12 shrink-0 items-center justify-between rounded-t bg-white/5 px-2"
      dataCy="space"
    >
      <div class="flex items-center gap-3 text-sm">
        <BaseIconClose data-cy="course-space-label" @click="onClose" />
        <BaseSpaceLogo class="!size-5" :space="space" />
        <div class="max-w-72 truncate">
          {{ space?.name }}
        </div>
      </div>
      <div
        class="flex size-6 cursor-pointer items-center justify-center rounded hover:bg-white/10"
      >
        <i class="fa-light fa-ellipsis" />
      </div>
    </div>
    <div class="hide-scrollbar h-0 flex-1 overflow-y-auto overscroll-contain">
      <div
        class="mb-2 flex cursor-pointer items-center gap-3 bg-white/5 p-4 text-white/50 hover:bg-white/10 hover:text-white"
        data-cy="fa62b6d59d435796"
        @click="onEditSpace"
      >
        <div
          class="relative flex size-12 items-center justify-center rounded border border-dashed border-white/50"
        >
          <BaseSpaceLogo
            v-if="space.id"
            class="!size-11 !rounded-sm !text-2xl"
            :space="space"
          />
          <i v-else class="fa-light fa-cloud-upload scale-125 text-xl" />
        </div>
        <div v-if="space.id">
          <div class="mb-0.5 text-sm text-white">{{ space.name }}</div>
          <div class="text-xs text-white/50">
            {{ $t('space.create.time', { time: timeAgo(space.createdAt) }) }}
          </div>
        </div>
        <div v-else>
          <div class="mb-0.5 text-sm text-white">
            {{ $t('space.create.title') }}
          </div>
          <div
            class="flex items-center gap-1 text-xs"
            :class="warning ? 'text-red-600' : 'text-white/50'"
          >
            <i class="fa-regular fa-circle-info" />
            <div>
              {{ $t('space.create.label') }}
            </div>
          </div>
        </div>
      </div>
      <div
        class="mb-2 cursor-pointer bg-white/5 p-4 text-white/50 hover:bg-white/10 hover:text-white"
        data-cy="edit-folder-icon"
        @click="onEditFolder"
      >
        <div class="mb-6 flex items-center justify-between px-2">
          <div class="flex items-center gap-3 text-sm text-white">
            <BaseIconFolder class="size-8" />
            {{ $t('space.folders') }}
          </div>
          <div class="text-xs">{{ space.numberOf?.folders || 0 }}</div>
        </div>
        <div class="flex items-center justify-between px-2">
          <div class="flex items-center gap-3 text-sm text-white">
            <div class="flex size-8 items-center justify-center">
              <i class="fa-solid fa-book text-base" />
            </div>
            {{ $t('org.about.course.label') }}
          </div>
          <div class="text-xs">{{ space.numberOf?.courses || 0 }}</div>
        </div>
      </div>
      <OrganizationHubSidebarMember
        v-if="space.id && !hubSidebar.course.state"
        type="space"
      />
    </div>
  </OrganizationHubSidebarWrap>
</template>

<script>
export default {
  setup() {
    const hubCourse = useHubCoursesStore();
    const hubSpaces = useHubSpacesStore();
    const hubSidebar = useHubSidebarStore();
    return { hubCourse, hubSpaces, hubSidebar };
  },
  data() {
    return {
      open: false,
      warning: false,
    };
  },
  computed: {
    space() {
      const { data } = this.hubSidebar.space;
      return this.hubSpaces.find(data.id) || data;
    },
    view() {
      return this.$route.query.view || 'grid';
    },
    creating() {
      return this.hubSidebar.space.creating;
    },
  },
  mounted() {
    setTimeout(() => {
      this.open = true;
    }, 100);

    if (this.hubSidebar.space.autoGenerated) {
      this.hubSidebar.space.autoGenerated = false;
      this.autoGenerated();
    }
  },
  methods: {
    onClose() {
      this.hubSidebar.state = false;
    },
    onEditSpace() {
      this.hubSidebar.space.state = true;
    },
    onEditFolder() {
      if (this.space.id) {
        this.hubSidebar.children.state = true;
      } else {
        this.warning = true;
      }
    },
    async autoGenerated() {
      try {
        this.hubSidebar.space.creating = true;
        const space = await this.hubSpaces.createSpace({
          autoGenerated: true,
        });
        this.hubSidebar.space.data = space;
        this.hubSpaces.spaces.push(space);
        // await this.hubSpaces.getSpaces();
        this.hubSidebar.space.creating = false;
      } catch (error) {
        this.hubSidebar.space.creating = false;
        this.hubSidebar.state = false;
        throw error;
      }
    },
  },
};
</script>
