export const countries = [
  {
    name: 'Austria',
    prefix: 43,
    flag: 'at',
    phonelength: 10,
  },
  {
    name: 'Belgium',
    prefix: 32,
    flag: 'be',
    phonelength: 9,
  },
  {
    name: 'Bulgaria',
    prefix: 359,
    flag: 'bg',
    phonelength: 9,
  },
  {
    name: 'Croatia',
    prefix: 385,
    flag: 'hr',
    phonelength: 9,
  },
  {
    name: 'Cyprus',
    prefix: 357,
    flag: 'cy',
    phonelength: 9,
  },
  {
    name: 'Czech Republic',
    prefix: 420,
    flag: 'cz',
    phonelength: 9,
  },
  {
    name: 'Denmark',
    prefix: 45,
    flag: 'dk',
    phonelength: 8,
  },
  {
    name: 'Estonia',
    prefix: 372,
    flag: 'ee',
    phonelength: 9,
  },
  {
    name: 'Finland',
    prefix: 358,
    flag: 'fi',
    phonelength: 12,
  },
  {
    name: 'France',
    prefix: 33,
    flag: 'fr',
    phonelength: 10,
  },
  {
    name: 'Germany',
    prefix: 49,
    flag: 'de',
    phonelength: 11,
  },
  {
    name: 'Greece',
    prefix: 30,
    flag: 'gr',
    phonelength: 10,
  },
  {
    name: 'Hungary',
    prefix: 36,
    flag: 'hu',
    phonelength: 9,
  },
  {
    name: 'Iceland',
    prefix: 354,
    flag: 'is',
    phonelength: 7,
  },
  {
    name: 'Republic of Ireland',
    prefix: 353,
    flag: 'ie',
    phonelength: 9,
  },
  {
    name: 'Italy',
    prefix: 39,
    flag: 'it',
    phonelength: 10,
  },
  {
    name: 'Latvia',
    prefix: 371,
    flag: 'lv',
    phonelength: 8,
  },
  {
    name: 'Liechtenstein',
    prefix: 423,
    flag: 'li',
    phonelength: 9,
  },
  {
    name: 'Lithuania',
    prefix: 370,
    flag: 'lt',
    phonelength: 8,
  },
  {
    name: 'Luxembourg',
    prefix: 352,
    flag: 'lu',
    phonelength: 9,
  },
  {
    name: 'Malta',
    prefix: 356,
    flag: 'mt',
    phonelength: 8,
  },
  {
    name: 'Netherlands',
    prefix: 31,
    flag: 'nl',
    phonelength: 9,
  },
  {
    name: 'Norway',
    prefix: 47,
    flag: 'no',
    phonelength: 8,
  },
  {
    name: 'Poland',
    prefix: 48,
    flag: 'pl',
    phonelength: 9,
  },
  {
    name: 'Portugal',
    prefix: 351,
    flag: 'pt',
    phonelength: 9,
  },
  {
    name: 'Romania',
    prefix: 40,
    flag: 'ro',
    phonelength: 9,
  },
  {
    name: 'Slovakia',
    prefix: 421,
    flag: 'sk',
    phonelength: 9,
  },
  {
    name: 'Slovenia',
    prefix: 386,
    flag: 'si',
    phonelength: 8,
  },
  {
    name: 'Spain',
    prefix: 34,
    flag: 'es',
    phonelength: 9,
  },
  {
    name: 'Sweden',
    prefix: 46,
    flag: 'se',
    phonelength: 9,
  },
];

// STRIPE支持的41个国家与货币信息
export const STRIPE_COUNTRIES = [
  {
    country_name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    phone_prefix: '+61',
    currency_symbol: '$',
    currency_code: 'AUD',
  },
  {
    country_name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    phone_prefix: '+43',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    phone_prefix: '+32',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    phone_prefix: '+359',
    currency_symbol: 'лв',
    currency_code: 'BGN',
  },
  {
    country_name: 'Canada',
    alpha2: 'CA',
    alpha3: 'CAN',
    phone_prefix: '+1',
    currency_symbol: '$',
    currency_code: 'CAD',
  },
  {
    country_name: 'Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    phone_prefix: '+385',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    phone_prefix: '+357',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Czech Republic',
    alpha2: 'CZ',
    alpha3: 'CZE',
    phone_prefix: '+420',
    currency_symbol: 'Kč',
    currency_code: 'CZK',
  },
  {
    country_name: 'Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    phone_prefix: '+45',
    currency_symbol: 'kr',
    currency_code: 'DKK',
  },
  {
    country_name: 'Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    phone_prefix: '+251',
    currency_symbol: 'Birr',
    currency_code: 'ETB',
  },
  {
    country_name: 'Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    phone_prefix: '+372',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    phone_prefix: '+358',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'France',
    alpha2: 'FR',
    alpha3: 'FRA',
    phone_prefix: '+33',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    phone_prefix: '+49',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Gibraltar',
    alpha2: 'GI',
    alpha3: 'GIB',
    phone_prefix: '+350',
    currency_symbol: '£',
    currency_code: 'GIP',
  },
  {
    country_name: 'Greece',
    alpha2: 'GR',
    alpha3: 'GRC',
    phone_prefix: '+30',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Hong Kong, China',
    alpha2: 'HK',
    alpha3: 'HKG',
    phone_prefix: '+852',
    currency_symbol: '$',
    currency_code: 'HKD',
  },
  {
    country_name: 'Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    phone_prefix: '+36',
    currency_symbol: 'Ft',
    currency_code: 'HUF',
  },
  {
    country_name: 'Ireland',
    alpha2: 'IE',
    alpha3: 'IRL',
    phone_prefix: '+353',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Italy',
    alpha2: 'IT',
    alpha3: 'ITA',
    phone_prefix: '+39',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Japan',
    alpha2: 'JP',
    alpha3: 'JPN',
    phone_prefix: '+81',
    currency_symbol: '¥',
    currency_code: 'JPY',
  },
  {
    country_name: 'Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    phone_prefix: '+371',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    phone_prefix: '+423',
    currency_symbol: 'CHF',
    currency_code: 'CHF',
  },
  {
    country_name: 'Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    phone_prefix: '+370',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    phone_prefix: '+352',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    phone_prefix: '+356',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    phone_prefix: '+31',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'New Zealand',
    alpha2: 'NZ',
    alpha3: 'NZL',
    phone_prefix: '+64',
    currency_symbol: '$',
    currency_code: 'NZD',
  },
  {
    country_name: 'Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    phone_prefix: '+47',
    currency_symbol: 'kr',
    currency_code: 'NOK',
  },
  {
    country_name: 'Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    phone_prefix: '+48',
    currency_symbol: 'zł',
    currency_code: 'PLN',
  },
  {
    country_name: 'Portugal',
    alpha2: 'PT',
    alpha3: 'PRT',
    phone_prefix: '+351',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Romania',
    alpha2: 'RO',
    alpha3: 'ROU',
    phone_prefix: '+40',
    currency_symbol: 'lei',
    currency_code: 'RON',
  },
  {
    country_name: 'Singapore',
    alpha2: 'SG',
    alpha3: 'SGP',
    phone_prefix: '+65',
    currency_symbol: '$',
    currency_code: 'SGD',
  },
  {
    country_name: 'Slovakia',
    alpha2: 'SK',
    alpha3: 'SVK',
    phone_prefix: '+421',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    phone_prefix: '+386',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    phone_prefix: '+34',
    currency_symbol: '€',
    currency_code: 'EUR',
  },
  {
    country_name: 'Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    phone_prefix: '+46',
    currency_symbol: 'kr',
    currency_code: 'SEK',
  },
  {
    country_name: 'Switzerland',
    alpha2: 'CH',
    alpha3: 'CHE',
    phone_prefix: '+41',
    currency_symbol: 'CHF',
    currency_code: 'CHF',
    country_flag_as_currency_flag: true,
  },
  {
    country_name: 'Thailand',
    alpha2: 'TH',
    alpha3: 'THA',
    phone_prefix: '+66',
    currency_symbol: '฿',
    currency_code: 'THB',
  },
  {
    country_name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    phone_prefix: '+971',
    currency_symbol: 'د.إ',
    currency_code: 'AED',
  },
  {
    country_name: 'United Kingdom',
    alpha2: 'GB',
    alpha3: 'GBR',
    phone_prefix: '+44',
    currency_symbol: '£',
    currency_code: 'GBP',
  },
  {
    country_name: 'United States',
    alpha2: 'US',
    alpha3: 'USA',
    phone_prefix: '+1',
    currency_symbol: '$',
    currency_code: 'USD',
    country_flag_as_currency_flag: true,
  },
  // 拓展欧盟
  {
    country_name: 'European Union',
    expanded: true,
    alpha2: 'EU',
    alpha3: 'EU',
    phone_prefix: '+1',
    currency_symbol: '€',
    currency_code: 'EUR',
    country_flag_as_currency_flag: true,
  },
  // 南非
  {
    country_name: 'South Africa',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    phone_prefix: '+27',
    currency_symbol: 'R',
    currency_code: 'ZAR',
  },
];
