export const profileEvent = {
  CLOSE_PROFILE_DRAWER: 'CLOSE_PROFILE_DRAWER',
  IAM_TAB_GET_DATA: 'IAM_TAB_GET_DATA',
  UPDATE_MAP: 'UPDATE_MAP',
  SHOW_USER_ON_MAP: 'SHOW_USER_ON_MAP',
  DELETE_PROFILE_QA_REVIEWS: 'DELETE_PROFILE_QA_REVIEWS',
};

export const courseEvent = {
  PURCHASED_SUCCESS: 'PURCHASED_SUCCESS',
  UPDATE_IAM_ROLE_COURSE: 'UPDATE_IAM_ROLE_COURSE',
  UPDATE_MANAGE_LICENSES_COURSE: 'UPDATE_MANAGE_LICENSES_COURSE',
};

export const paymentEvent = {
  SUB_SERVICE_SUCCESS: 'PAYMENT/SUB_SERVICE_SUCCESS',
};
